name = "Farwater Create"
version = "Season 8 v1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a1504dab0ee382f78457110935a8b3da9f1941cdb896fccb3615eb031f97072"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
