name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27aabe4b71881af2fbacb0aac66b8e503e077659116a6fb7d0ccf4523e8f7247"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
