// priority: 1

const outputBlacklist = [
  // AE2
  "ae2:spatial_anchor",
  "ae2:matter_cannon",
  "ae2:tiny_tnt",
  // Create
  "create:tree_fertilizer",
  "create:blaze_cake",
  "create:postion_extension_pole",
  "create:belt_connector",
  "create:brass_funnel",
  "create:brass_tunnel",
  "createaddition:diamond_grit",
   // Supplementaries
  "supplementaries:crank",
  "supplementaries:bellows",
  "supplementaries:crystal_display",
  "supplementaries:faucet",
  "supplementaries:cage",
  "supplementaries:rope_arrow",
  "supplementaries:notice_board",
  "supplementaries:quiver",
  "supplementaries:bomb",
  "supplementaries:bomb_blue",
  "supplementaries:bomb_blue_projectile",
  "supplementaries:bomb_projectile",
  "supplementaries:bomb_spiky",
  "supplementaries:bomb_spiky_projectile",
  "supplementaries:iron_gate",
  "supplementaries:speaker_block",
  "supplementaries:relayer",
  "supplementaries:cog_block",
  "supplementaries:turn_table",
  "supplementaries:clock_block",
  "supplementaries:spring_launcher",
  "supplementaries:redstone_illuminator",
  "supplementaries:wrench",
  "supplementaries:pulley_block",
    
    // Kibe
  "kibe:cursed_dirt",
  "kibe:cursed_seeds",
  "kibe:cursed_droplets",
  "kibe:entangled_tank",
  "kibe:entangled_chest",
  "kibe:entangled_bag",
  "kibe:entangled_bucket",
  "kibe:drawbridge",
  "kibe:liquid_xp_bucket",
  "kibe:white_rune",
  "kibe:orange_rune",
  "kibe:magenta_rune",
  "kibe:light_blue_rune",
  "kibe:yellow_rune",
  "kibe:lime_rune",
  "kibe:light_gray_rune",
  "kibe:cyan_rune",
  "kibe:blue_rune",
  "kibe:purple_rune",
  "kibe:green_rune",
  "kibe:brown_rune",
  "kibe:red_rune",
  "kibe:pink_rune",
  "kibe:black_rune",
  "kibe:gray_rune",
  "kibe:chunk_loader",
  "kibe:wooden_bucket",
  "kibe:void_bucket",
  "kibe:slime_sling",
  "kibe:torch_sling",
  "kibe:xp_drain",
  "kibe:xp_shower",
  "kibe:regular_conveyor_belt",
  "kibe:fast_conveyor_belt",
  "kibe:express_conveyor_belt",
  "kibe:tank",
  "kibe:white_elevator",
  "kibe:orange_elevator",
  "kibe:magenta_elevator",
  "kibe:light_blue_elevator",
  "kibe:yellow_elevator",
  "kibe:lime_elevator",
  "kibe:light_gray_elevator",
  "kibe:cyan_elevator",
  "kibe:blue_elevator",
  "kibe:purple_levator",
  "kibe:green_elevator",
  "kibe:brown_elevator",
  "kibe:red_elevator",
  "kibe:black_elevator",
  "kibe:gray_elevator",
  "kibe:pink_elevator",
  "kibe:purple_elevator",
  "kibe:kibe",
  "kibe:cursed_kibe",
  "kibe:golden_kibe",
  "kibe:diamond_kibe",
  "kibe:light_ring",
  "kibe:drawbridge",
  "kibe:wither_builder",
  "kibe:fluid_hopper",
  "kibe:angel_ring",
  "kibe:stone_spikes",
  "kibe:iron_spikes",
  "kibe:gold_spikes",
  "kibe:diamond_spikes",
   // POWAH
  "powah:ender_cell_starter",
  "powah:ender_cell_basic",
  "powah:ender_cell_hardened",
  "powah:ender_cell_blazing",
  "powah:ender_cell_niotic",
  "powah:ender_cell_spirited",
  "powah:ender_cell_nitro",
  "powah:ender_gate_starter",
  "powah:ender_gate_basic",
  "powah:ender_gate_hardened",
  "powah:ender_gate_blazing",
  "powah:ender_gate_niotic",
  "powah:ender_gate_spirited",
  "powah:ender_gate_nitro",
  // Vinery
  "vinery:vinemaker_apron",
];

const recipeBlackList = [
  "minecraft:ender_eye",
  // "ae2:network/parts/annihilation_plane_alt2",
  // "ae2:network/parts/annihilation_plane_alt",
  // "ae2:network/parts/annihilation_plane_alt",
]

const modBlackList = ["waystones", "inmis"];

ServerEvents.recipes(e => {
  console.log("loading blacklist..")
  outputBlacklist.forEach((item) => e.remove({ output: item }));
  recipeBlackList.forEach((recipe) => e.remove({ id: recipe }));
  modBlackList.forEach((mod) => e.remove({ mod: mod }));
});
